# 다음 yaml 코드를 이용하여 gitaction workflow demo를 실행해 본다.
name: GitActions Demo1
on: push
jobs:
  GitActions-demo-job:
    name: Demo Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a environment
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: hyunyong
          LAST_NAME: lee
          AWS_JOB_NAME: kevin.lee
        run: |
          echo $MY_VAR $FIRST_NAME $LAST_NAME.
          echo $MY_VAR $AWS_JOB_NAME.
