# 다음 yaml 코드를 이용하여 gitaction workflow demo를 실행해 본다.
name: GitActions-Demo2
on: [push]
jobs:
  GitActions-demo-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job.triggered.event is ${{ github.event_name }}"
      - run: echo "job.running.os is ${{ runner.os }}"
      - run: echo "job.branch is ${{ github.ref }}"
      - run: echo "job.repository is ${{ github.repository }}"
      - run: echo "job.status is ${{ job.status }}."
      - run: echo "The workflow is code test on the runner."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files on repository
        run: |
          ls ${{ github.workspace }}
